In [18]:

import os
import pandas as pd
import geopandas as gpd

from pathlib import Path
from sqlalchemy import create_engine, text
from geoalchemy2 import Geometry

#### Define file paths

In [19]:
DATA_DIR = Path("../data/citibike")

citibike_path = DATA_DIR / "JC2025.csv"
weather_path = DATA_DIR / "jersey_weather_2025.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

#### Connection String

In [20]:
DB_USER = "postgres"
DB_PASSWORD = "password"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "citibike"

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)


DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

#### Parameters with Masking

In [21]:
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")


DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)


DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

In [22]:
engine = create_engine(DATABASE_URL)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/citibike)

#### Testing The connections

In [23]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT version();"))
    print(result.fetchone()[0])

PostgreSQL 17.0 (Debian 17.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

#### Testing The connections

In [24]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT PostGIS_Version();"))
    print(result.fetchone()[0])

3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

#### Loading the Citibike Data
##### Defining Data Paths
###### Adjust paths based on your course project structure.

In [25]:
DATA_DIR = Path("../data/citibike/JC")

citibike_path = DATA_DIR / "JC2025.csv"
weather_path = DATA_DIR / "jersey_weather_2025.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

#### Reading Citi Bike CSV

In [26]:
citibike_df = pd.read_csv("../data/citibike/JC2025.csv")

citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,40.742677,-74.051789,member
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,40.711130,-74.078900,member
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,40.735938,-74.030305,member

In [27]:
citibike_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual'],
      dtype='str')

#### Cleaning Data Types

In [28]:
citibike_df["started_at"] = pd.to_datetime(
    citibike_df["started_at"],
    errors="coerce"
)

citibike_df["ended_at"] = pd.to_datetime(
    citibike_df["ended_at"],
    errors="coerce"
)

In [29]:
#Create a date column for easier joins with weather data.
citibike_df["ride_date"] = citibike_df["started_at"].dt.date

citibike_df["ride_date"] = pd.to_datetime(
    citibike_df["ride_date"],
    errors="coerce"
)

citibike_df[
    [
        "ride_id",
        "started_at",
        "ended_at",
        "ride_date"
    ]
].head()

            ride_id              started_at                ended_at  ride_date
0  880A0159BA5275FB 2025-01-16 17:50:49.136 2025-01-16 17:57:00.710 2025-01-16
1  1A5E1E274B2AF0AD 2025-01-31 06:10:41.818 2025-01-31 06:22:09.499 2025-01-31
2  EA9928D3C05B8377 2025-01-09 16:42:50.213 2025-01-09 17:04:12.870 2025-01-09
3  3C42C367750B9292 2025-01-21 16:14:14.398 2025-01-21 16:37:10.458 2025-01-21
4  94D3B0265A7BDE1F 2025-01-30 16:38:18.840 2025-01-30 17:04:08.166 2025-01-30

#### Writing Citi Bike Data to PostGIS Database
###### Although the database has PostGIS, this first table is still normal tabular data.

In [30]:
import numpy as np

# 1. Առաջին 50,000 տողը գրում ենք՝ ջնջելով հին աղյուսակը (if_exists="replace")
chunk_size = 50000
first_chunk = citibike_df.iloc[:chunk_size]

first_chunk.to_sql(
    name="jersey_city",
    con=engine,
    if_exists="replace",  # Առաջին անգամ հինը փոխարինում ենք
    index=False
)

# 2. Մնացած բոլոր տողերը ավելացնում ենք հերթով (if_exists="append")
for i in range(chunk_size, len(citibike_df), chunk_size):
    chunk = citibike_df.iloc[i : i + chunk_size]
    chunk.to_sql(
        name="jersey_city",
        con=engine,
        if_exists="append",  # Մնացած մասերը ավելացնում ենք վերջից
        index=False
    )
    print(f"Տեղափոխվեց {i + len(chunk)} տող...")
print("Բոլոր տվյալները հաջողությամբ տեղափոխվեցին:")

Տեղափոխվեց 100000 տող...
Տեղափոխվեց 150000 տող...
Տեղափոխվեց 200000 տող...
Տեղափոխվեց 250000 տող...
Տեղափոխվեց 300000 տող...
Տեղափոխվեց 350000 տող...
Տեղափոխվեց 400000 տող...
Տեղափոխվեց 450000 տող...
Տեղափոխվեց 500000 տող...
Տեղափոխվեց 550000 տող...
Տեղափոխվեց 600000 տող...
Տեղափոխվեց 650000 տող...
Տեղափոխվեց 700000 տող...
Տեղափոխվեց 750000 տող...
Տեղափոխվեց 800000 տող...

PendingRollbackError: Can't reconnect until invalid transaction is rolled back.  Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)

#### Checking the resutls

In [ ]:
query = """
SELECT
    
    *

FROM jersey_city
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

#### Loading Weather Data

In [ ]:
weather_df = pd.read_csv('../data/citibike/JC/jersey_weather_2025.csv')

weather_df.head()