In [53]:

import os
import pandas as pd
import geopandas as gpd

from pathlib import Path
from sqlalchemy import create_engine, text
from geoalchemy2 import Geometry

#### Define file paths

In [55]:
DATA_DIR = Path("../data/citibike/JC")

citibike_path = DATA_DIR / "JC_Enriched.csv"
weather_path = DATA_DIR / "jersey_weather.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

#### Connection String

In [56]:
DB_USER = "postgres"
DB_PASSWORD = "password"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "citibike"

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)


DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

#### Parameters with Masking

In [57]:
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")


DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)


DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

In [58]:
engine = create_engine(DATABASE_URL)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/citibike)

#### Testing The connections

In [59]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT PostGIS_Version();"))
    print(result.fetchone()[0])

3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

#### Testing The connections

In [60]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT PostGIS_Version();"))
    print(result.fetchone()[0])

3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

#### Loading the Citibike Data
##### Defining Data Paths
###### Adjust paths based on your course project structure.

In [61]:
DATA_DIR = Path("../data/citibike/JC")

citibike_path = DATA_DIR / "JC_Enriched.csv"
weather_path = DATA_DIR / "jersey_weather.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

#### Reading Citi Bike CSV

In [62]:
citibike_df = pd.read_csv("../data/citibike/JC/JC_Enriched.csv")

citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,end_lng,member_casual,year,ride_duration_minutes,date,month,month_name,day_of_week,hour,season
0,40FBC7AEEBB220EC,electric_bike,2026-01-11 15:01:01.954,2026-01-11 15:16:57.103,14 St Ferry - 14 St & Shipyard Ln,HB202,Pier 61 at Chelsea Piers,6233.04,40.752961,-74.024353,...,-74.00821,member,2026,15.919150,2026-01-11,2026-01,January,Sunday,15,Winter
1,47FB1CA65D3F7E0F,electric_bike,2026-01-16 11:49:41.364,2026-01-16 11:58:27.291,14 St Ferry - 14 St & Shipyard Ln,HB202,Madison St & 1 St,HB402,40.752961,-74.024353,...,-74.03930,member,2026,8.765450,2026-01-16,2026-01,January,Friday,11,Winter
2,BFB10DE1E40F3709,electric_bike,2026-01-07 19:55:41.424,2026-01-07 19:59:09.874,Church Sq Park - 5 St & Park Ave,HB601,Madison St & 1 St,HB402,40.742659,-74.032233,...,-74.03930,member,2026,3.474167,2026-01-07,2026-01,January,Wednesday,19,Winter
3,F16B896495AAF618,electric_bike,2026-01-24 11:12:10.547,2026-01-24 11:34:42.801,Madison St & 1 St,HB402,Madison St & 1 St,HB402,40.738790,-74.039300,...,-74.03930,member,2026,22.537567,2026-01-24,2026-01,January,Saturday,11,Winter
4,76D77D5F1D491B3C,electric_bike,2026-01-22 20:58:00.602,2026-01-22 21:02:39.088,Clinton St & 7 St,HB303,Madison St & 1 St,HB402,40.745420,-74.033320,...,-74.03930,casual,2026,4.641433,2026-01-22,2026-01,January,Thursday,20,Winter

In [64]:
citibike_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'year', 'ride_duration_minutes', 'date', 'month',
       'month_name', 'day_of_week', 'hour', 'season'],
      dtype='str')

#### Cleaning Data Types

In [65]:
citibike_df["started_at"] = pd.to_datetime(
    citibike_df["started_at"],
    errors="coerce"
)

citibike_df["ended_at"] = pd.to_datetime(
    citibike_df["ended_at"],
    errors="coerce"
)

In [66]:
#Create a date column for easier joins with weather data.
citibike_df["ride_date"] = citibike_df["started_at"].dt.date

citibike_df["ride_date"] = pd.to_datetime(
    citibike_df["ride_date"],
    errors="coerce"
)

citibike_df[
    [
        "ride_id",
        "started_at",
        "ended_at",
        "ride_date"
    ]
].head()

            ride_id              started_at                ended_at  ride_date
0  40FBC7AEEBB220EC 2026-01-11 15:01:01.954 2026-01-11 15:16:57.103 2026-01-11
1  47FB1CA65D3F7E0F 2026-01-16 11:49:41.364 2026-01-16 11:58:27.291 2026-01-16
2  BFB10DE1E40F3709 2026-01-07 19:55:41.424 2026-01-07 19:59:09.874 2026-01-07
3  F16B896495AAF618 2026-01-24 11:12:10.547 2026-01-24 11:34:42.801 2026-01-24
4  76D77D5F1D491B3C 2026-01-22 20:58:00.602 2026-01-22 21:02:39.088 2026-01-22

#### Writing Citi Bike Data to PostGIS Database
###### Although the database has PostGIS, this first table is still normal tabular data.

In [67]:
import numpy as np

# 1. Write the first 50,000 rows, replacing the old table (if_exists="replace")
chunk_size = 50000
first_chunk = citibike_df.iloc[:chunk_size]

first_chunk.to_sql(
    name="jersey_city",
    con=engine,
    if_exists="replace",  # Replace the table for the first batch
    index=False
)

# 2. Append the remaining rows sequentially (if_exists="append")
for i in range(chunk_size, len(citibike_df), chunk_size):
    chunk = citibike_df.iloc[i : i + chunk_size]
    chunk.to_sql(
        name="jersey_city",
        con=engine,
        if_exists="append",  # Append the rest of the data
        index=False
    )
    print(f"Moved {i + len(chunk)} lines...")
print("All data has been successfully transferred.")

Moved 100000 lines...
Moved 150000 lines...
Moved 200000 lines...
Moved 250000 lines...
Moved 300000 lines...
Moved 350000 lines...
Moved 400000 lines...
Moved 450000 lines...
Moved 500000 lines...
Moved 550000 lines...
Moved 600000 lines...
Moved 650000 lines...
Moved 700000 lines...
Moved 750000 lines...
Moved 800000 lines...
Moved 825700 lines...
All data has been successfully transferred.

#### Checking the resutls

In [68]:
query = """
SELECT
    
    *

FROM jersey_city
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,member_casual,year,ride_duration_minutes,date,month,month_name,day_of_week,hour,season,ride_date
0,40FBC7AEEBB220EC,electric_bike,2026-01-11 15:01:01.954,2026-01-11 15:16:57.103,14 St Ferry - 14 St & Shipyard Ln,HB202,Pier 61 at Chelsea Piers,6233.04,40.752961,-74.024353,...,member,2026,15.919150,2026-01-11,2026-01,January,Sunday,15,Winter,2026-01-11
1,47FB1CA65D3F7E0F,electric_bike,2026-01-16 11:49:41.364,2026-01-16 11:58:27.291,14 St Ferry - 14 St & Shipyard Ln,HB202,Madison St & 1 St,HB402,40.752961,-74.024353,...,member,2026,8.765450,2026-01-16,2026-01,January,Friday,11,Winter,2026-01-16
2,BFB10DE1E40F3709,electric_bike,2026-01-07 19:55:41.424,2026-01-07 19:59:09.874,Church Sq Park - 5 St & Park Ave,HB601,Madison St & 1 St,HB402,40.742659,-74.032233,...,member,2026,3.474167,2026-01-07,2026-01,January,Wednesday,19,Winter,2026-01-07
3,F16B896495AAF618,electric_bike,2026-01-24 11:12:10.547,2026-01-24 11:34:42.801,Madison St & 1 St,HB402,Madison St & 1 St,HB402,40.738790,-74.039300,...,member,2026,22.537567,2026-01-24,2026-01,January,Saturday,11,Winter,2026-01-24
4,76D77D5F1D491B3C,electric_bike,2026-01-22 20:58:00.602,2026-01-22 21:02:39.088,Clinton St & 7 St,HB303,Madison St & 1 St,HB402,40.745420,-74.033320,...,casual,2026,4.641433,2026-01-22,2026-01,January,Thursday,20,Winter,2026-01-22

#### Loading Weather Data

In [69]:
weather_df = pd.read_csv('../data/citibike/JC/jersey_weather.csv')

weather_df.head()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

In [70]:
weather_df["date"] = pd.to_datetime(
    weather_df["date"],
    errors="coerce"
)

weather_df.head()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

In [71]:
weather_df.to_sql(
    name="jersey_weather",
    con=engine,
    if_exists="replace",
    index=False
)

559

In [72]:
query = """
SELECT
    
    *

FROM   jersey_weather

LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

In [73]:
neighborhood_gdf = gpd.read_file(neighborhood_path)

neighborhood_gdf.head()

,cartodb_id,area_sq_ft,acres,area,neighborhood,color,lon,lat,geometry
0,38,411601381.8,9449.068,Greenville,Port Liberte,NaN,-74.074540,40.694202,"POLYGON ((-74.06862 40.70098, -74.06808 40.696..."
1,52,411601381.8,9449.068,Bergen-Lafayette,LSP Industrial,NaN,-74.062358,40.699189,"POLYGON ((-74.06808 40.69684, -74.06862 40.700..."
2,29,411601381.8,9449.068,West Side,Hackensack,NaN,-74.085147,40.735520,"POLYGON ((-74.07601 40.73822, -74.07781 40.737..."
3,35,411601381.8,9449.068,Bergen-Lafayette,Lafayette,12.0,-74.061279,40.712676,"POLYGON ((-74.056 40.71735, -74.056 40.71692, ..."
4,51,411601381.8,9449.068,Greenville,Jackson Hill,15.0,-74.085503,40.700791,"POLYGON ((-74.07561 40.70233, -74.0758 40.7020..."

In [74]:
neighborhood_gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [75]:
neighborhood_gdf = neighborhood_gdf.to_crs("EPSG:4326")

neighborhood_gdf.geom_type.value_counts()

Polygon    53
Name: count, dtype: int64

In [76]:
neighborhood_gdf.to_postgis(
    name="jersey_city_neighborhoods",
    con=engine,
    if_exists="replace",
    index=False
)

In [77]:
query = """
SELECT
   
   *
   
FROM jersey_city_neighborhoods
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,cartodb_id,area_sq_ft,acres,area,neighborhood,color,lon,lat,geometry
0,38,411601381.8,9449.068,Greenville,Port Liberte,NaN,-74.074540,40.694202,0103000020E6100000010000002E0300005FD06A586484...
1,52,411601381.8,9449.068,Bergen-Lafayette,LSP Industrial,NaN,-74.062358,40.699189,0103000020E61000000100000027000000AF9CC1805B84...
2,29,411601381.8,9449.068,West Side,Hackensack,NaN,-74.085147,40.735520,0103000020E610000001000000840000002697EF6ADD84...
3,35,411601381.8,9449.068,Bergen-Lafayette,Lafayette,12.0,-74.061279,40.712676,0103000020E610000001000000190000001AA825769583...
4,51,411601381.8,9449.068,Greenville,Jackson Hill,15.0,-74.085503,40.700791,0103000020E6100000010000002000000057337AC7D684...

In [78]:
query = """
SELECT
    neighborhood,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jersey_city_neighborhoods
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

     neighborhood geometry_type  srid
0    Port Liberte    ST_Polygon  4326
1  LSP Industrial    ST_Polygon  4326
2      Hackensack    ST_Polygon  4326
3       Lafayette    ST_Polygon  4326
4    Jackson Hill    ST_Polygon  4326

In [79]:
start_stations = citibike_df[
    [
        "ride_id",
        "start_station_id",
        "start_station_name",
        "start_lat",
        "start_lng"
    ]
].copy()

start_stations = start_stations.rename(
    columns={
        "start_station_id": "station_id",
        "start_station_name": "station_name",
        "start_lat": "lat",
        "start_lng": "lng"
    }
)

start_stations["activity_type"] = "departure"

In [80]:
end_stations = citibike_df[
    [
        "ride_id",
        "end_station_id",
        "end_station_name",
        "end_lat",
        "end_lng"
    ]
].copy()

end_stations = end_stations.rename(
    columns={
        "end_station_id": "station_id",
        "end_station_name": "station_name",
        "end_lat": "lat",
        "end_lng": "lng"
    }
)

end_stations["activity_type"] = "arrival"

In [81]:
station_activity_long = pd.concat(
    [
        start_stations,
        end_stations
    ],
    ignore_index=True
)

station_activity_long = station_activity_long.dropna(
    subset=[
        "station_id",
        "station_name",
        "lat",
        "lng"
    ]
)

In [82]:
station_activity_agg = (
    station_activity_long
    .groupby(
        [
            "station_id",
            "station_name",
            "lat",
            "lng",
            "activity_type"
        ],
        as_index=False
    )
    .agg(
        number_of_rides=("ride_id", "count")
    )
)

In [83]:
station_summary = (
    station_activity_agg
    .pivot_table(
        index=[
            "station_id",
            "station_name",
            "lat",
            "lng"
        ],
        columns="activity_type",
        values="number_of_rides",
        fill_value=0
    )
    .reset_index()
)

station_summary.columns.name = None

station_summary = station_summary.rename(
    columns={
        "departure": "total_departures",
        "arrival": "total_arrivals"
    }
)

if "total_departures" not in station_summary.columns:
    station_summary["total_departures"] = 0

if "total_arrivals" not in station_summary.columns:
    station_summary["total_arrivals"] = 0

station_summary["total_activity"] = (
    station_summary["total_departures"] +
    station_summary["total_arrivals"]
)

station_summary["net_departures"] = (
    station_summary["total_departures"] -
    station_summary["total_arrivals"]
)

station_summary = station_summary.sort_values(
    "total_activity",
    ascending=False
).reset_index(drop=True)

station_summary.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures
0,JC115,Grove St PATH,40.719410,-74.043090,38846.0,38162.0,77008.0,-684.0
1,HB106,River St & Newark St,40.736722,-74.029007,30436.0,29018.0,59454.0,-1418.0
2,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,22050.0,21826.0,43876.0,-224.0
3,JC109,Bergen Ave & Sip Ave,40.731009,-74.064437,19450.0,19696.0,39146.0,246.0
4,JC009,Hamilton Park,40.727596,-74.044247,17976.0,17882.0,35858.0,-94.0

In [84]:
station_gdf = gpd.GeoDataFrame(
    station_summary,
    geometry=gpd.points_from_xy(
        station_summary["lng"],
        station_summary["lat"]
    ),
    crs="EPSG:4326"
)

station_gdf.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures,geometry
0,JC115,Grove St PATH,40.719410,-74.043090,38846.0,38162.0,77008.0,-684.0,POINT (-74.04309 40.71941)
1,HB106,River St & Newark St,40.736722,-74.029007,30436.0,29018.0,59454.0,-1418.0,POINT (-74.02901 40.73672)
2,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,22050.0,21826.0,43876.0,-224.0,POINT (-74.0303 40.73594)
3,JC109,Bergen Ave & Sip Ave,40.731009,-74.064437,19450.0,19696.0,39146.0,246.0,POINT (-74.06444 40.73101)
4,JC009,Hamilton Park,40.727596,-74.044247,17976.0,17882.0,35858.0,-94.0,POINT (-74.04425 40.7276)

In [85]:
station_gdf.to_postgis(
    name="jc_stations",
    con=engine,
    if_exists="replace",
    index=False
)

In [86]:
query = """
SELECT
    station_id,
    station_name,
    total_activity,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jc_stations
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,station_id,station_name,total_activity,geometry_type,srid
0,JC115,Grove St PATH,77008.0,ST_Point,4326
1,HB106,River St & Newark St,59454.0,ST_Point,4326
2,HB101,Hoboken Terminal - Hudson St & Hudson Pl,43876.0,ST_Point,4326
3,JC109,Bergen Ave & Sip Ave,39146.0,ST_Point,4326
4,JC009,Hamilton Park,35858.0,ST_Point,4326

##### Create Materialized View with SQLAlchemy