In [1]:

import os
import pandas as pd
import numpy as np
import geopandas as gpd

from pathlib import Path
from sqlalchemy import create_engine, text
from geoalchemy2 import Geometry

#### Define file paths

In [2]:
DATA_DIR = Path("../data/citibike/JC")

citibike_path = DATA_DIR / "JC_Enriched.csv"
weather_path = DATA_DIR / "jersey_weather.csv"
neighborhood_path = DATA_DIR / "jersey-city-neighborhoods.geojson"

#### Define Database Connection

In [3]:
DB_USER = "postgres"
DB_PASSWORD = "password"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "citibike"

DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)


DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

#### Parameters with Masking

In [4]:
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOST = os.getenv("DB_HOST")
DB_PORT = os.getenv("DB_PORT")
DB_NAME = os.getenv("DB_NAME")


DATABASE_URL = (
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}"
    f"@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)


DATABASE_URL

'postgresql+psycopg2://postgres:password@localhost:5432/citibike'

#### Define engine

In [5]:
engine = create_engine(DATABASE_URL)

engine

Engine(postgresql+psycopg2://postgres:***@localhost:5432/citibike)

#### Testing the connections

In [6]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT PostGIS_Version();"))
    print(result.fetchone()[0])

3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

#### Loading Data

In [7]:
# Reading Citibike CSV
citibike_df = pd.read_csv("../data/citibike/JC/JC_Enriched.csv")

citibike_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,end_lng,member_casual,year,ride_duration_minutes,date,month,month_name,day_of_week,hour,season
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,...,-74.051789,member,2025,6.192900,2025-01-16,2025-01,January,Thursday,17,Winter
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,...,-74.078900,member,2025,11.461350,2025-01-31,2025-01,January,Friday,6,Winter
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,...,-74.030305,member,2025,21.377617,2025-01-09,2025-01,January,Thursday,16,Winter
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,...,-74.030305,member,2025,22.934333,2025-01-21,2025-01,January,Tuesday,16,Winter
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,...,-74.030305,member,2025,25.822100,2025-01-30,2025-01,January,Thursday,16,Winter

In [8]:
citibike_df.columns

Index(['ride_id', 'rideable_type', 'started_at', 'ended_at',
       'start_station_name', 'start_station_id', 'end_station_name',
       'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng',
       'member_casual', 'year', 'ride_duration_minutes', 'date', 'month',
       'month_name', 'day_of_week', 'hour', 'season'],
      dtype='str')

#### Cleaning Data Types

In [9]:
citibike_df["started_at"] = pd.to_datetime(
    citibike_df["started_at"],
    errors="coerce"
)

citibike_df["ended_at"] = pd.to_datetime(
    citibike_df["ended_at"],
    errors="coerce"
)

In [10]:
#Create a date column for easier joins with weather data.
citibike_df["ride_date"] = citibike_df["started_at"].dt.date

citibike_df["ride_date"] = pd.to_datetime(
    citibike_df["ride_date"],
    errors="coerce"
)

citibike_df[
    [
        "ride_id",
        "started_at",
        "ended_at",
        "ride_date"
    ]
].head()

            ride_id              started_at                ended_at  ride_date
0  880A0159BA5275FB 2025-01-16 17:50:49.136 2025-01-16 17:57:00.710 2025-01-16
1  1A5E1E274B2AF0AD 2025-01-31 06:10:41.818 2025-01-31 06:22:09.499 2025-01-31
2  EA9928D3C05B8377 2025-01-09 16:42:50.213 2025-01-09 17:04:12.870 2025-01-09
3  3C42C367750B9292 2025-01-21 16:14:14.398 2025-01-21 16:37:10.458 2025-01-21
4  94D3B0265A7BDE1F 2025-01-30 16:38:18.840 2025-01-30 17:04:08.166 2025-01-30

#### Writing Citibike Data to PostGIS Database

In [11]:
with engine.connect() as conn:
    # Drop the table and all dependent views
    conn.execute(text("DROP TABLE IF EXISTS jersey_city CASCADE;"))
    conn.commit()
    print("Table dropped successfully.")

Table dropped successfully.

In [12]:
# 1. Write the first 50,000 rows and replace the existing table (if_exists="replace")
chunk_size = 50000
first_chunk = citibike_df.iloc[:chunk_size]

first_chunk.to_sql(
    name="jersey_city",
    con=engine,
    if_exists="replace",  # Replace the table for the first batch
    index=False
)

# 2. Append the remaining rows sequentially (if_exists="append")
for i in range(chunk_size, len(citibike_df), chunk_size):
    chunk = citibike_df.iloc[i : i + chunk_size]
    chunk.to_sql(
        name="jersey_city",
        con=engine,
        if_exists="append",  # Append the rest of the data
        index=False
    )
    print(f"Moved {i + len(chunk)} rows...")
print("All data has been successfully transferred.")

Moved 100000 rows...
Moved 150000 rows...
Moved 200000 rows...
Moved 250000 rows...
Moved 300000 rows...
Moved 350000 rows...
Moved 400000 rows...
Moved 450000 rows...
Moved 500000 rows...
Moved 550000 rows...
Moved 600000 rows...
Moved 650000 rows...
Moved 700000 rows...
Moved 750000 rows...
Moved 800000 rows...
Moved 850000 rows...
Moved 900000 rows...
Moved 950000 rows...
Moved 1000000 rows...
Moved 1050000 rows...
Moved 1100000 rows...
Moved 1150000 rows...
Moved 1200000 rows...
Moved 1250000 rows...
Moved 1300000 rows...
Moved 1350000 rows...
Moved 1400000 rows...
Moved 1450000 rows...
Moved 1500000 rows...
Moved 1520835 rows...
All data has been successfully transferred.

In [13]:
# Check the results
query = """
SELECT
    
    *

FROM jersey_city
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,...,member_casual,year,ride_duration_minutes,date,month,month_name,day_of_week,hour,season,ride_date
0,880A0159BA5275FB,electric_bike,2025-01-16 17:50:49.136,2025-01-16 17:57:00.710,Hilltop,JC019,Pershing Field,JC024,40.731169,-74.057574,...,member,2025,6.192900,2025-01-16,2025-01,January,Thursday,17,Winter,2025-01-16
1,1A5E1E274B2AF0AD,electric_bike,2025-01-31 06:10:41.818,2025-01-31 06:22:09.499,Hilltop,JC019,Jackson Square,JC063,40.731169,-74.057574,...,member,2025,11.461350,2025-01-31,2025-01,January,Friday,6,Winter,2025-01-31
2,EA9928D3C05B8377,classic_bike,2025-01-09 16:42:50.213,2025-01-09 17:04:12.870,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,...,member,2025,21.377617,2025-01-09,2025-01,January,Thursday,16,Winter,2025-01-09
3,3C42C367750B9292,electric_bike,2025-01-21 16:14:14.398,2025-01-21 16:37:10.458,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,...,member,2025,22.934333,2025-01-21,2025-01,January,Tuesday,16,Winter,2025-01-21
4,94D3B0265A7BDE1F,classic_bike,2025-01-30 16:38:18.840,2025-01-30 17:04:08.166,Hilltop,JC019,Hoboken Terminal - Hudson St & Hudson Pl,HB101,40.731169,-74.057574,...,member,2025,25.822100,2025-01-30,2025-01,January,Thursday,16,Winter,2025-01-30

#### Loading Weather Data

In [14]:
# Read Weather CSV
weather_df = pd.read_csv('../data/citibike/JC/jersey_weather.csv')

weather_df.head()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

In [15]:
# Convert Date Column
weather_df["date"] = pd.to_datetime(
    weather_df["date"],
    errors="coerce"
)

weather_df.head()

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05

In [16]:
# Write Weather Data to Database
weather_df.to_sql(
    name="jersey_weather",
    con=engine,
    if_exists="replace",
    index=False
)

602

In [17]:
# Check the results
query = """
SELECT
    
    *

FROM   jersey_weather

LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,date
0,11.0,3.9,7.4,4.5,4.5,0.0,23.2,2025-01-01
1,5.4,0.3,2.6,0.0,0.0,0.0,25.1,2025-01-02
2,3.2,-1.9,0.4,0.0,0.0,0.0,17.1,2025-01-03
3,-0.1,-2.7,-1.4,0.0,0.0,0.0,26.1,2025-01-04
4,0.4,-3.6,-2.2,0.0,0.0,0.0,19.9,2025-01-05


#### Load Neighborhood GeoJSON as Spatial Table

In [18]:
# Read GeoJSON with GeoPandas
neighborhood_gdf = gpd.read_file(neighborhood_path)

neighborhood_gdf.head()

,cartodb_id,area_sq_ft,acres,area,neighborhood,color,lon,lat,geometry
0,38,411601381.8,9449.068,Greenville,Port Liberte,NaN,-74.074540,40.694202,"POLYGON ((-74.06862 40.70098, -74.06808 40.696..."
1,52,411601381.8,9449.068,Bergen-Lafayette,LSP Industrial,NaN,-74.062358,40.699189,"POLYGON ((-74.06808 40.69684, -74.06862 40.700..."
2,29,411601381.8,9449.068,West Side,Hackensack,NaN,-74.085147,40.735520,"POLYGON ((-74.07601 40.73822, -74.07781 40.737..."
3,35,411601381.8,9449.068,Bergen-Lafayette,Lafayette,12.0,-74.061279,40.712676,"POLYGON ((-74.056 40.71735, -74.056 40.71692, ..."
4,51,411601381.8,9449.068,Greenville,Jackson Hill,15.0,-74.085503,40.700791,"POLYGON ((-74.07561 40.70233, -74.0758 40.7020..."

In [19]:
# Checking the crs
neighborhood_gdf.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [20]:
# neighborhood_gdf = neighborhood_gdf.to_crs("EPSG:4326")

In [21]:
# Inspect Geometry Type
neighborhood_gdf.geom_type.value_counts()

Polygon    53
Name: count, dtype: int64

In [22]:
# Write GeoDataFrame to PostGIS
neighborhood_gdf.to_postgis(
    name="jersey_city_neighborhoods",
    con=engine,
    if_exists="replace",
    index=False
)

In [23]:
# Check Spatial Table
query = """
SELECT
   
   *
   
FROM jersey_city_neighborhoods
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,cartodb_id,area_sq_ft,acres,area,neighborhood,color,lon,lat,geometry
0,38,411601381.8,9449.068,Greenville,Port Liberte,NaN,-74.074540,40.694202,0103000020E6100000010000002E0300005FD06A586484...
1,52,411601381.8,9449.068,Bergen-Lafayette,LSP Industrial,NaN,-74.062358,40.699189,0103000020E61000000100000027000000AF9CC1805B84...
2,29,411601381.8,9449.068,West Side,Hackensack,NaN,-74.085147,40.735520,0103000020E610000001000000840000002697EF6ADD84...
3,35,411601381.8,9449.068,Bergen-Lafayette,Lafayette,12.0,-74.061279,40.712676,0103000020E610000001000000190000001AA825769583...
4,51,411601381.8,9449.068,Greenville,Jackson Hill,15.0,-74.085503,40.700791,0103000020E6100000010000002000000057337AC7D684...

#### Create Station Spatial Table

In [24]:
# The ride table has start and end coordinates, but we also want a station-level spatial table.

query = """
SELECT
    neighborhood,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jersey_city_neighborhoods
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

     neighborhood geometry_type  srid
0    Port Liberte    ST_Polygon  4326
1  LSP Industrial    ST_Polygon  4326
2      Hackensack    ST_Polygon  4326
3       Lafayette    ST_Polygon  4326
4    Jackson Hill    ST_Polygon  4326

#### Create Station Summary

In [25]:
start_stations = citibike_df[
    [
        "ride_id",
        "start_station_id",
        "start_station_name",
        "start_lat",
        "start_lng"
    ]
].copy()

start_stations = start_stations.rename(
    columns={
        "start_station_id": "station_id",
        "start_station_name": "station_name",
        "start_lat": "lat",
        "start_lng": "lng"
    }
)

start_stations["activity_type"] = "departure"

In [26]:
end_stations = citibike_df[
    [
        "ride_id",
        "end_station_id",
        "end_station_name",
        "end_lat",
        "end_lng"
    ]
].copy()

end_stations = end_stations.rename(
    columns={
        "end_station_id": "station_id",
        "end_station_name": "station_name",
        "end_lat": "lat",
        "end_lng": "lng"
    }
)

end_stations["activity_type"] = "arrival"

In [27]:
# Combine departure and arrival station records and remove rows with missing station information.

station_activity_long = pd.concat(
    [
        start_stations,
        end_stations
    ],
    ignore_index=True
)

station_activity_long = station_activity_long.dropna(
    subset=[
        "station_id",
        "station_name",
        "lat",
        "lng"
    ]
)

In [28]:
# Aggregate ride activity by station and activity type.

station_activity_agg = (
    station_activity_long
    .groupby(
        [
            "station_id",
            "station_name",
            "lat",
            "lng",
            "activity_type"
        ],
        as_index=False
    )
    .agg(
        number_of_rides=("ride_id", "count")
    )
)

In [29]:
# Create a station-level summary of departures, arrivals, and total activity.

station_summary = (
    station_activity_agg
    .pivot_table(
        index=[
            "station_id",
            "station_name",
            "lat",
            "lng"
        ],
        columns="activity_type",
        values="number_of_rides",
        fill_value=0
    )
    .reset_index()
)

station_summary.columns.name = None

station_summary = station_summary.rename(
    columns={
        "departure": "total_departures",
        "arrival": "total_arrivals"
    }
)

if "total_departures" not in station_summary.columns:
    station_summary["total_departures"] = 0

if "total_arrivals" not in station_summary.columns:
    station_summary["total_arrivals"] = 0

station_summary["total_activity"] = (
    station_summary["total_departures"] +
    station_summary["total_arrivals"]
)

station_summary["net_departures"] = (
    station_summary["total_departures"] -
    station_summary["total_arrivals"]
)

station_summary = station_summary.sort_values(
    "total_activity",
    ascending=False
).reset_index(drop=True)

station_summary.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures
0,JC115,Grove St PATH,40.719410,-74.043090,72137.0,69081.0,141218.0,-3056.0
1,HB106,River St & Newark St,40.736722,-74.029007,41074.0,39377.0,80451.0,-1697.0
2,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,40029.0,39187.0,79216.0,-842.0
3,JC009,Hamilton Park,40.727596,-74.044247,33724.0,33595.0,67319.0,-129.0
4,JC109,Bergen Ave & Sip Ave,40.731009,-74.064437,32614.0,32833.0,65447.0,219.0

In [30]:
# Convert Station Summary to GeoDataFrame

station_gdf = gpd.GeoDataFrame(
    station_summary,
    geometry=gpd.points_from_xy(
        station_summary["lng"],
        station_summary["lat"]
    ),
    crs="EPSG:4326"
)

station_gdf.head()

,station_id,station_name,lat,lng,total_arrivals,total_departures,total_activity,net_departures,geometry
0,JC115,Grove St PATH,40.719410,-74.043090,72137.0,69081.0,141218.0,-3056.0,POINT (-74.04309 40.71941)
1,HB106,River St & Newark St,40.736722,-74.029007,41074.0,39377.0,80451.0,-1697.0,POINT (-74.02901 40.73672)
2,HB101,Hoboken Terminal - Hudson St & Hudson Pl,40.735938,-74.030305,40029.0,39187.0,79216.0,-842.0,POINT (-74.0303 40.73594)
3,JC009,Hamilton Park,40.727596,-74.044247,33724.0,33595.0,67319.0,-129.0,POINT (-74.04425 40.7276)
4,JC109,Bergen Ave & Sip Ave,40.731009,-74.064437,32614.0,32833.0,65447.0,219.0,POINT (-74.06444 40.73101)

In [31]:
#Write Station Points to PostGIS

station_gdf.to_postgis(
    name="jc_stations",
    con=engine,
    if_exists="replace",
    index=False
)

In [32]:
#Check Station Spatial Table

query = """
SELECT
    station_id,
    station_name,
    total_activity,
    ST_GeometryType(geometry) AS geometry_type,
    ST_SRID(geometry) AS srid
FROM jc_stations
LIMIT 5;
"""

pd.read_sql(
    query,
    con=engine
)

,station_id,station_name,total_activity,geometry_type,srid
0,JC115,Grove St PATH,141218.0,ST_Point,4326
1,HB106,River St & Newark St,80451.0,ST_Point,4326
2,HB101,Hoboken Terminal - Hudson St & Hudson Pl,79216.0,ST_Point,4326
3,JC009,Hamilton Park,67319.0,ST_Point,4326
4,JC109,Bergen Ave & Sip Ave,65447.0,ST_Point,4326

##### Create Materialized View with SQLAlchemy

In [33]:
create_tableau_materialized_view_sql = """
DROP MATERIALIZED VIEW IF EXISTS mv_tableau_citibike_dashboard;

CREATE MATERIALIZED VIEW mv_tableau_citibike_dashboard AS
WITH ride_base AS (
    SELECT
        c.ride_id,
        c.rideable_type,
        c.member_casual,

        c.started_at,
        c.ended_at,
        c.started_at::date AS ride_date,

        EXTRACT(YEAR FROM c.started_at)::int AS ride_year,
        EXTRACT(QUARTER FROM c.started_at)::int AS ride_quarter,
        EXTRACT(MONTH FROM c.started_at)::int AS ride_month,
        TO_CHAR(c.started_at, 'Month') AS ride_month_name,
        TO_CHAR(c.started_at, 'Day') AS ride_day_of_week,
        EXTRACT(ISODOW FROM c.started_at)::int AS ride_day_number,
        EXTRACT(HOUR FROM c.started_at)::int AS ride_hour,

        CASE
            WHEN EXTRACT(ISODOW FROM c.started_at) IN (6, 7)
                THEN 'Weekend'
            ELSE 'Weekday'
        END AS weekday_type,

        EXTRACT(EPOCH FROM (c.ended_at - c.started_at)) / 60.0 AS ride_duration_minutes,

        c.start_station_id,
        c.start_station_name,
        c.end_station_id,
        c.end_station_name,

        c.start_lat,
        c.start_lng,
        c.end_lat,
        c.end_lng,

        ST_SetSRID(
            ST_MakePoint(c.start_lng, c.start_lat),
            4326
        ) AS start_geom,

        ST_SetSRID(
            ST_MakePoint(c.end_lng, c.end_lat),
            4326
        ) AS end_geom

    FROM jersey_city AS c
    WHERE
        c.ride_id IS NOT NULL
        AND c.started_at IS NOT NULL
        AND c.ended_at IS NOT NULL
        AND c.ended_at > c.started_at
        AND c.start_lat IS NOT NULL
        AND c.start_lng IS NOT NULL
        AND c.end_lat IS NOT NULL
        AND c.end_lng IS NOT NULL
)

SELECT
    r.ride_id,
    r.rideable_type,
    r.member_casual,

    r.started_at,
    r.ended_at,
    r.ride_date,
    r.ride_year,
    r.ride_quarter,
    r.ride_month,
    TRIM(r.ride_month_name) AS ride_month_name,
    TRIM(r.ride_day_of_week) AS ride_day_of_week,
    r.ride_day_number,
    r.ride_hour,
    r.weekday_type,

    r.ride_duration_minutes,

    r.start_station_id,
    r.start_station_name,
    r.end_station_id,
    r.end_station_name,

    r.start_lat,
    r.start_lng,
    r.end_lat,
    r.end_lng,

    start_n.neighborhood AS start_neighborhood,
    end_n.neighborhood AS end_neighborhood,

    ST_Distance(
        r.start_geom::geography,
        r.end_geom::geography
    ) / 1000.0 AS distance_km,

    CASE
        WHEN ST_Distance(r.start_geom::geography, r.end_geom::geography) / 1000.0 < 1
            THEN 'Short'
        WHEN ST_Distance(r.start_geom::geography, r.end_geom::geography) / 1000.0 < 3
            THEN 'Medium'
        ELSE 'Long'
    END AS distance_group,

    CASE
        WHEN r.ride_duration_minutes < 10
            THEN 'Short'
        WHEN r.ride_duration_minutes < 30
            THEN 'Medium'
        ELSE 'Long'
    END AS duration_group,

    w.temperature_2m_max,
    w.temperature_2m_min,
    w.temperature_2m_mean,
    w.precipitation_sum,
    w.rain_sum,
    w.snowfall_sum,
    w.wind_speed_10m_max,

    CASE
        WHEN w.precipitation_sum > 0
            THEN 'Precipitation'
        ELSE 'No Precipitation'
    END AS precipitation_flag,

    CASE
        WHEN w.temperature_2m_mean < 0
            THEN 'Freezing'
        WHEN w.temperature_2m_mean < 10
            THEN 'Cold'
        WHEN w.temperature_2m_mean < 20
            THEN 'Mild'
        ELSE 'Warm'
    END AS temperature_group

FROM ride_base AS r

LEFT JOIN jersey_weather AS w
    ON r.ride_date = w.date::date

LEFT JOIN jersey_city_neighborhoods AS start_n
    ON ST_Within(r.start_geom, start_n.geometry)

LEFT JOIN jersey_city_neighborhoods AS end_n
    ON ST_Within(r.end_geom, end_n.geometry);
"""

In [34]:
with engine.begin() as connection:
    connection.execute(text(create_tableau_materialized_view_sql))

##### Check the Materialized View

In [35]:
query = """
SELECT *
FROM mv_tableau_citibike_dashboard
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,rideable_type,member_casual,started_at,ended_at,ride_date,ride_year,ride_quarter,ride_month,ride_month_name,...,duration_group,temperature_2m_max,temperature_2m_min,temperature_2m_mean,precipitation_sum,rain_sum,snowfall_sum,wind_speed_10m_max,precipitation_flag,temperature_group
0,F70CE58DEEF978B9,electric_bike,casual,2024-12-31 23:47:38.670,2025-01-01 00:14:23.861,2024-12-31,2024,4,12,December,...,Medium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No Precipitation,Warm
1,2F943CCBC130864A,electric_bike,member,2025-01-01 11:59:16.169,2025-01-01 12:02:18.502,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
2,1337693A7F756751,electric_bike,member,2025-01-01 16:22:35.983,2025-01-01 16:25:02.539,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
3,6B67963A6B3347AA,electric_bike,casual,2025-01-01 14:05:30.351,2025-01-01 14:13:26.141,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
4,1AC0AC51BD941E6C,electric_bike,casual,2025-01-01 02:21:42.996,2025-01-01 02:27:20.464,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
5,81B4BCC2AF00F857,classic_bike,member,2025-01-01 12:22:25.026,2025-01-01 12:27:25.381,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
6,CAB066CF80780F62,classic_bike,member,2025-01-01 16:43:47.518,2025-01-01 16:46:43.744,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
7,7BFDA8C975AAAFD1,classic_bike,member,2025-01-01 10:53:51.485,2025-01-01 10:55:06.135,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
8,3DF63EDDC804325D,electric_bike,member,2025-01-01 17:28:51.855,2025-01-01 17:37:02.509,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold
9,366F4C3F5070F0D3,electric_bike,member,2025-01-01 15:22:18.608,2025-01-01 15:24:53.815,2025-01-01,2025,1,1,January,...,Short,11.0,3.9,7.4,4.5,4.5,0.0,23.2,Precipitation,Cold

##### Check Number of Rows

In [36]:
query = """
SELECT
    COUNT(*) AS number_of_rows
FROM mv_tableau_citibike_dashboard;
"""

pd.read_sql(
    query,
    con=engine
)

   number_of_rows
0         1520835

##### Check Data Quality

In [37]:
query = """
SELECT
    COUNT(*) AS total_rides,

    COUNT(temperature_2m_mean) AS rides_with_weather,
    COUNT(*) - COUNT(temperature_2m_mean) AS rides_missing_weather,

    COUNT(start_neighborhood) AS rides_with_start_neighborhood,
    COUNT(*) - COUNT(start_neighborhood) AS rides_missing_start_neighborhood,

    COUNT(end_neighborhood) AS rides_with_end_neighborhood,
    COUNT(*) - COUNT(end_neighborhood) AS rides_missing_end_neighborhood,

    COUNT(distance_km) AS rides_with_distance,
    COUNT(*) - COUNT(distance_km) AS rides_missing_distance
FROM mv_tableau_citibike_dashboard;
"""

pd.read_sql(
    query,
    con=engine
)

,total_rides,rides_with_weather,rides_missing_weather,rides_with_start_neighborhood,rides_missing_start_neighborhood,rides_with_end_neighborhood,rides_missing_end_neighborhood,rides_with_distance,rides_missing_distance
0,1520835,1520833,2,834496,686339,827764,693071,1520835,0

##### Create Indexes on the Materialized View

In [38]:

with engine.begin() as connection:
    connection.execute(text("""
        CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_tableau_ride_id
        ON mv_tableau_citibike_dashboard (ride_id);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_date
        ON mv_tableau_citibike_dashboard (ride_date);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_month
        ON mv_tableau_citibike_dashboard (ride_year, ride_month);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_ride_hour
        ON mv_tableau_citibike_dashboard (ride_hour);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_member_casual
        ON mv_tableau_citibike_dashboard (member_casual);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_rideable_type
        ON mv_tableau_citibike_dashboard (rideable_type);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_start_station
        ON mv_tableau_citibike_dashboard (start_station_name);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_end_station
        ON mv_tableau_citibike_dashboard (end_station_name);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_start_neighborhood
        ON mv_tableau_citibike_dashboard (start_neighborhood);
    """))

    connection.execute(text("""
        CREATE INDEX IF NOT EXISTS idx_mv_tableau_end_neighborhood
        ON mv_tableau_citibike_dashboard (end_neighborhood);
    """))

##### Refresh Materialized View

In [39]:
with engine.begin() as connection:
    connection.execute(
        text("REFRESH MATERIALIZED VIEW mv_tableau_citibike_dashboard;")
    )

##### Concurrent Refresh

In [40]:
with engine.begin() as connection:
    connection.execute(
        text("REFRESH MATERIALIZED VIEW CONCURRENTLY mv_tableau_citibike_dashboard;")
    )

##### Create Helper Function to Refresh the Dashboard View

In [41]:

def refresh_tableau_dashboard_view(engine, concurrently=False):
    if concurrently:
        refresh_sql = """
        REFRESH MATERIALIZED VIEW CONCURRENTLY mv_tableau_citibike_dashboard;
        """
    else:
        refresh_sql = """
        REFRESH MATERIALIZED VIEW mv_tableau_citibike_dashboard;
        """

    with engine.begin() as connection:
        connection.execute(text(refresh_sql))

In [42]:

refresh_tableau_dashboard_view(
    engine=engine,
    concurrently=True
)

##### Preview Fields for Tableau

In [43]:
query = """
SELECT
    ride_id,
    ride_date,
    ride_month_name,
    ride_day_of_week,
    weekday_type,
    ride_hour,
    rideable_type,
    member_casual,
    start_station_name,
    end_station_name,
    start_neighborhood,
    end_neighborhood,
    ride_duration_minutes,
    duration_group,
    distance_km,
    distance_group,
    temperature_2m_mean,
    temperature_group,
    precipitation_sum,
    precipitation_flag,
    rain_sum,
    snowfall_sum,
    wind_speed_10m_max
FROM mv_tableau_citibike_dashboard
LIMIT 10;
"""

pd.read_sql(
    query,
    con=engine
)

,ride_id,ride_date,ride_month_name,ride_day_of_week,weekday_type,ride_hour,rideable_type,member_casual,start_station_name,end_station_name,...,duration_group,distance_km,distance_group,temperature_2m_mean,temperature_group,precipitation_sum,precipitation_flag,rain_sum,snowfall_sum,wind_speed_10m_max
0,C75B3E85372716FD,2024-12-31,December,Tuesday,Weekday,23,electric_bike,member,Van Vorst Park,Grove St PATH,...,Medium,0.404888,Short,NaN,Warm,NaN,No Precipitation,NaN,NaN,NaN
1,F70CE58DEEF978B9,2024-12-31,December,Tuesday,Weekday,23,electric_bike,casual,Van Vorst Park,Grove St PATH,...,Medium,0.404888,Short,NaN,Warm,NaN,No Precipitation,NaN,NaN,NaN
2,2741F7C137F93AA2,2025-01-01,January,Wednesday,Weekday,15,electric_bike,member,Jersey & 3rd,Van Vorst Park,...,Short,0.558269,Short,7.4,Cold,4.5,Precipitation,4.5,0.0,23.2
3,9CFD5B0D7E12145A,2025-01-01,January,Wednesday,Weekday,17,electric_bike,member,McGinley Square,McGinley Square,...,Short,0.000000,Short,7.4,Cold,4.5,Precipitation,4.5,0.0,23.2
4,803D8753C6D2B5DD,2025-01-01,January,Wednesday,Weekday,1,electric_bike,member,Hoboken Terminal - River St & Hudson Pl,Adams St & 2 St,...,Short,0.777549,Short,7.4,Cold,4.5,Precipitation,4.5,0.0,23.2
5,2AD632607E0C8A62,2025-01-01,January,Wednesday,Weekday,12,classic_bike,member,Jersey & 3rd,Van Vorst Park,...,Short,0.558269,Short,7.4,Cold,4.5,Precipitation,4.5,0.0,23.2
6,393A3385A13B84E5,2025-01-01,January,Wednesday,Weekday,21,electric_bike,member,Church Sq Park - 5 St & Park Ave,11 St & Washington St,...,Medium,0.919814,Short,7.4,Cold,4.5,Precipitation,4.5,0.0,23.2
7,FB73DBFD1206EBA5,2025-01-01,January,Wednesday,Weekday,11,classic_bike,member,Morris Canal,City Hall,...,Short,0.741767,Short,7.4,Cold,4.5,Precipitation,4.5,0.0,23.2
8,23D860FC9FC2ABEB,2025-01-01,January,Wednesday,Weekday,11,electric_bike,member,Southwest Park - Jackson St & Observer Hwy,Church Sq Park - 5 St & Park Ave,...,Short,0.977891,Short,7.4,Cold,4.5,Precipitation,4.5,0.0,23.2
9,A992BC8494E6C8FF,2025-01-01,January,Wednesday,Weekday,20,electric_bike,casual,Southwest Park - Jackson St & Observer Hwy,Church Sq Park - 5 St & Park Ave,...,Short,0.977891,Short,7.4,Cold,4.5,Precipitation,4.5,0.0,23.2